name: Deploy to Development

on:
  push:
    branches:
      - development # Trigger on push to the development branch

jobs:
  deploy:
    name: Deploy to ECS Development
    runs-on: ubuntu-latest

    steps:
      # Checkout the code repository (optional, not required for deployment)
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Authenticate with AWS
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_SECRET }}
          aws-region: ap-southeast-1 # Specify your AWS region

      # Authenticate Docker with ECR
      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 779846799056.dkr.ecr.ap-southeast-1.amazonaws.com/anybirdie/fab-booking-service

      # Update ECS Service
      - name: Deploy to ECS
        run: |
          aws ecs update-service \
            --cluster development-cluster \
            --service development-service \
            --force-new-deployment

            